spring:
  config:
    import: optional:classpath:application-secret.yml
  profiles:
    active: prod

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

naver:
  ocr:
    secret_key: ${OCR_SECRET_KEY}
    invoke_url: ${OCR_API_INVOKE_URL}
