spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/sunsak-db # db 파일 경로 수정 - 오류나서
    username: sa #오류나서 수정..
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  data: #redis 설정 추가
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  config:
    import: application-secret.yml
  profiles: # 추가
    include: secret
    active: prod

server:
  port: 8080 # default port

jwt: #jwt key
  secret: Ke9hqr5rC2N9ehW4q8zenXHgmme1dmnpMJhB2rwxrB9XfLKpWIkNdwI6Fd2fwaqYG15I/yGtnjBaNtFEmyXpOg==

naver:
  ocr:
    secret_key: ${OCR_SECRET_KEY}
    invoke_url: ${OCR_API_INVOKE_URL}