spring:
  datasource:
    url: jdbc:mysql://sunsak-db-1.cva48mgg09q4.ap-northeast-2.rds.amazonaws.com/sunsak
    username: # 나중에 설정
    password: # 나중에 설정
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost # EC2 내부에서 Redis 도는 경우
      port: 6379
      password: ${REDIS_PASSWORD}