spring:
  config:
    activate:
      on-profile: default
    import: application-secret.yml

  profiles:
    include: secret
    active: dev  # 기본값은 dev (로컬 개발 기준)

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

naver:
  ocr:
    secret_key: ${OCR_SECRET_KEY}
    invoke_url: ${OCR_API_INVOKE_URL}
