spring: # rds 연결 안되는 문제로 수정
  config:
    import: application-secret.yml

  profiles:
    active: prod
    include: secret

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

naver:
  ocr:
    secret_key: ${OCR_SECRET_KEY}
    invoke_url: ${OCR_API_INVOKE_URL}
