name: Deploy to EC2

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Gradle 캐시 자동 관리 + wrapper 검증
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build (skip tests)
        run: ./gradlew build -x test

      - name: List build outputs
        run: ls -alh build/libs

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "~/sunsak/build/libs/"
          overwrite: true

      - name: Symlink latest jar & restart via systemd
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -euxo pipefail
            cd ~/sunsak/build/libs

            # 최신 "실제 파일" JAR 선택 (app.jar 심볼릭 링크 제외)
            LATEST=$(find . -maxdepth 1 -type f -name "*.jar" ! -name "app.jar" -printf "%T@ %p\n" \
              | sort -nr | head -n1 | awk '{print $2}')

            if [ -z "${LATEST}" ]; then
              echo "No candidate JAR found (except app.jar)"; exit 1
            fi

            # 심볼릭 링크 갱신 (같은 타겟이어도 안전)
            ln -sfn "${LATEST}" app.jar

            # 서비스 재시작 & 상태 확인
            sudo systemctl restart sunsak
            sudo systemctl --no-pager --full status sunsak || true
