name: Deploy to EC2

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Gradle 캐시 자동 관리(+wrapper 검증)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build (skip tests)
        run: ./gradlew build -x test

      # (선택) 빌드 산출물 확인 로그
      - name: List build outputs
        run: ls -alh build/libs

      # SSH known_hosts 등록 (scp/ssh에서 호스트키 경고 방지)
      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # JAR EC2로 복사 (대상 폴더 보장)
      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "~/sunsak/build/libs/"
          overwrite: true

      # EC2에서 앱 재기동 (nohup 방식)
      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 15m
          # 애플리케이션이 환경변수 읽어쓰면 여기서 주입됨
          envs: |
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            OCR_SECRET_KEY=${{ secrets.OCR_SECRET_KEY }}
            OCR_API_INVOKE_URL=${{ secrets.OCR_API_INVOKE_URL }}
          script: |
            set -euxo pipefail
            cd ~/sunsak
            mkdir -p build/libs
            # 기존 프로세스 종료
            pkill -f 'java -jar' || true
            # 최신 JAR 선택
            JAR_PATH=$(ls -t build/libs/*.jar | head -n 1)
            # 백그라운드 실행 (로그 저장)
            nohup env \
              MYSQL_USER="$MYSQL_USER" \
              MYSQL_PASSWORD="$MYSQL_PASSWORD" \
              REDIS_PASSWORD="$REDIS_PASSWORD" \
              JWT_SECRET="$JWT_SECRET" \
              OCR_SECRET_KEY="$OCR_SECRET_KEY" \
              OCR_API_INVOKE_URL="$OCR_API_INVOKE_URL" \
              java -jar "$JAR_PATH" > ../log.out 2>&1 &
            sleep 3
            pgrep -af 'java -jar' || (echo "App failed to start" && exit 1)
