name: Deploy to EC2

on:
  push:
    branches:
      - develop  # 배포 트리거 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) (선택) 호스트 키 자동 등록
      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and run deploy
        uses: appleboy/ssh-action@v1.0.0
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OCR_SECRET_KEY: ${{ secrets.OCR_SECRET_KEY }}
          OCR_API_INVOKE_URL: ${{ secrets.OCR_API_INVOKE_URL }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          # 변수 "이름만" 나열 (값 아님)
          envs: MYSQL_USER,MYSQL_PASSWORD,REDIS_PASSWORD,JWT_SECRET,OCR_SECRET_KEY,OCR_API_INVOKE_URL
          script: |
            set -euxo pipefail
            cd ~/sunsak
            git pull origin develop
            chmod +x deploy.sh

            # 진짜로 ENV가 들어왔는지 확인
            env | grep -E 'MYSQL|REDIS|JWT|OCR' || true

            ./deploy.sh
